/* Generated By:JavaCC: Do not edit this line. JavaCCParserConstants.java */
package jminusminus;

public interface JavaCCParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int ABSTRACT = 8;
  int BOOLEAN = 9;
  int CHAR = 10;
  int CLASS = 11;
  int ELSE = 12;
  int EXTENDS = 13;
  int FALSE = 14;
  int IF = 15;
  int IMPORT = 16;
  int INSTANCEOF = 17;
  int INT = 18;
  int NEW = 19;
  int NULL = 20;
  int PACKAGE = 21;
  int PRIVATE = 22;
  int PROTECTED = 23;
  int PUBLIC = 24;
  int RETURN = 25;
  int STATIC = 26;
  int SUPER = 27;
  int THIS = 28;
  int TRUE = 29;
  int VOID = 30;
  int WHILE = 31;
  int BREAK = 32;
  int BYTE = 33;
  int CASE = 34;
  int CATCH = 35;
  int CONST = 36;
  int CONTINUE = 37;
  int DEFAULT_KEY = 38;
  int DO = 39;
  int DOUBLE = 40;
  int FINAL = 41;
  int FINALLY = 42;
  int FLOAT = 43;
  int FOR = 44;
  int GOTO = 45;
  int IMPLEMENTS = 46;
  int INTERFACE = 47;
  int LONG = 48;
  int NATIVE = 49;
  int SHORT = 50;
  int STRICTFP = 51;
  int SWITCH = 52;
  int SYNCHRONIZED = 53;
  int THROW = 54;
  int THROWS = 55;
  int TRANSIENT = 56;
  int TRY = 57;
  int VOLATILE = 58;
  int PLUS = 59;
  int ASSIGN = 60;
  int DEC = 61;
  int EQUAL = 62;
  int GT = 63;
  int INC = 64;
  int LAND = 65;
  int LNOT = 66;
  int BAND = 67;
  int BOR = 68;
  int BXOR = 69;
  int MINUS = 70;
  int PLUS_ASSIGN = 71;
  int STAR = 72;
  int COMPLEMENT = 73;
  int DIV = 74;
  int MOD = 75;
  int ALSHIFT = 76;
  int ARSHIFT = 77;
  int LRSHIFT = 78;
  int TER = 79;
  int NEQ = 80;
  int DIV_ASSIGN = 81;
  int MINUS_ASSIGN = 82;
  int STAR_ASSIGN = 83;
  int MOD_ASSIGN = 84;
  int ARSHIFT_ASSIGN = 85;
  int LRSHIFT_ASSIGN = 86;
  int ALSHIFT_ASSIGN = 87;
  int BXOR_ASSIGN = 88;
  int BOR_ASSIGN = 89;
  int LOR = 90;
  int BAND_ASSIGN = 91;
  int LT = 92;
  int LEQ = 93;
  int GEQ = 94;
  int LPAREN = 95;
  int RPAREN = 96;
  int LCURLY = 97;
  int RCURLY = 98;
  int LBRACK = 99;
  int RBRACK = 100;
  int SEMI = 101;
  int COMMA = 102;
  int DOT = 103;
  int COLON = 104;
  int IDENTIFIER = 105;
  int LETTER = 106;
  int DIGIT = 107;
  int NON_ZERO_DIGIT = 108;
  int INT_LITERAL = 109;
  int DOUBLE_LITERAL = 110;
  int CHAR_LITERAL = 111;
  int STRING_LITERAL = 112;
  int ESC = 113;
  int ERROR = 114;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<SINGLE_LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"abstract\"",
    "\"boolean\"",
    "\"char\"",
    "\"class\"",
    "\"else\"",
    "\"extends\"",
    "\"false\"",
    "\"if\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"static\"",
    "\"super\"",
    "\"this\"",
    "\"true\"",
    "\"void\"",
    "\"while\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"implements\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"short\"",
    "\"strictfp\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"try\"",
    "\"volatile\"",
    "\"+\"",
    "\"=\"",
    "\"--\"",
    "\"==\"",
    "\">\"",
    "\"++\"",
    "\"&&\"",
    "\"!\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"-\"",
    "\"+=\"",
    "\"*\"",
    "\"~\"",
    "\"/\"",
    "\"%\"",
    "\"<<\"",
    "\">>\"",
    "\">>>\"",
    "\"?\"",
    "\"!=\"",
    "\"/=\"",
    "\"-=\"",
    "\"*=\"",
    "\"%=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"<<=\"",
    "\"^=\"",
    "\"|=\"",
    "\"||\"",
    "\"&=\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\":\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<NON_ZERO_DIGIT>",
    "<INT_LITERAL>",
    "<DOUBLE_LITERAL>",
    "<CHAR_LITERAL>",
    "<STRING_LITERAL>",
    "<ESC>",
    "<ERROR>",
  };

}
